export const SET_RAW_RESULTS = 'SET_RAW_RESULTS';
export const SET_SINGLE_RESULTS = 'SET_SINGLE_RESULTS';
export const SET_RESULTS_IN_COLUMN = 'SET_RESULTS_IN_COLUMN';
export const SET_PARTIES = 'SET_PARTIES';
export const SET_THRESHOLDS = 'SET_THRESHOLDS';
export const SET_DISTRICTS = 'SET_DISTRICTS';
export const SET_PERCENTAGE_VOTES = 'SET_PERCENTAGE_VOTES';
